function [newData1] = importmedpc(fileToRead1)
%IMPORTFILE1(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 17-Feb-2020 16:11:40

DELIMITER = '[]';
HEADERLINES = 32;

% Import the file
newData1 = importdata(fileToRead1);

