version: "3.4"
x-shared: &common
  ipc: host
  image: zhuokund/datascience-notebook:cuda11.4.0-python3.8
  volumes:
    - ../../:/src/
    - /ssh-agent:/ssh-agent
  env_file:
    - .env

services:
  notebook:
    <<: *common
    container_name: ${JUPYTER_NAME}
    ports:
      - "${JUPYTER_HOST:-0.0.0.0}:${JUPYTER_PORT_CONTAINER:-8888}:8888"
    entrypoint: jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token="${JUPYTER_PASSWORD:-}" --no-browser
