version: "3.4"
x-shared: &common
  ipc: host
  image: zhuokund/datascience-notebook:cuda11.4.0-python3.8
  volumes:
    - ../../:/src/
  env_file:
    - .env

services:
  notebook:
    <<: *common
    container_name: ${JUPYTER_NAME}
    ports:
      - "${JUPYTER_HOST:-0.0.0.0}:${JUPYTER_PORT_CONTAINER:-8888}:8888"
    entrypoint: ["/src/odor_grin_lens/deploy/notebook.sh",]
